'use client';

import { Amplify } from 'aws-amplify';
import { generateClient, type Client } from 'aws-amplify/data';
import outputs from '../../amplify_outputs.json';
import type { Schema } from '../../amplify/data/resource';

/**
 * `amplify_outputs.json` is generated by `npx ampx sandbox` (or by Amplify
 * Hosting at build time) and is deliberately not committed. A placeholder is
 * written by `scripts/ensure-outputs.mjs` so the app still builds without AWS
 * credentials — this flag is how the UI tells the two apart.
 */
export const backendConfigured = Boolean(
  (outputs as { auth?: { user_pool_id?: string } }).auth?.user_pool_id
);

if (backendConfigured) {
  Amplify.configure(outputs as Parameters<typeof Amplify.configure>[0], { ssr: true });
}

let cached: Client<Schema> | null = null;

/** Lazily created so importing this module never throws on an unconfigured build. */
export function getClient(): Client<Schema> {
  if (!cached) cached = generateClient<Schema>();
  return cached;
}
